ClinicForAnimal1.2/Models/Reviews/Review.cs
namespace ClinicForAnimal1._2.Models.Reviews
{

    public partial class Review
    {
        public int Id { get; set; }
        public string NameOfPatient { get; set; }
        public string Review1 { get; set; }
    }
}

ClinicForAnimal1.2/Models/Reviews/ReviewsForPerson.Context.cs
namespace ClinicForAnimal1._2.Models.Reviews
{
    using System.Data.Entity;

    public partial class ReviewsEntity : DbContext
    {
        public ReviewsEntity()
            : base("name=ReviewsEntity")
        {
        }
   
    
        public virtual DbSet<Review> Reviews { get; set; }
    }
}

ClinicForAnimal1.2/Models/Reviews/ReviewsForPerson.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Vlad\Documents\Visual Studio 2015\Projects\Новая папка\отзывы\ClinicForAnimal1.2\ClinicForAnimal1.2\Models\Reviews\ReviewsForPerson.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

ClinicForAnimal1.2/Models/Reviews/ReviewsForPerson.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

ClinicForAnimal1.2/Controllers/AdminController.cs
using System.Web.Mvc;

namespace ClinicForAnimal1._2.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        public ActionResult InfoForAdmin()
        {
            return View();
        }
    }
}

ClinicForAnimal1.2/Controllers/CartForPatients1Controller.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ClinicForAnimal1._2.Models.PatientCart;
using System.Collections.Generic;

namespace ClinicForAnimal1._2.Controllers
{
    
    [Authorize]
    public class CartForPatients1Controller : Controller
    {
        PatientCart db = new PatientCart();
        [Authorize(Roles = "doctor,admin")]
        public ActionResult Index()
        {
            var a = db.CartForPatient.Include(c => c.AspNetUser);
            return View(a.ToList());
        }

        [Authorize(Roles = "doctor,admin")]
        [HttpGet]
        public ActionResult Create()
        {
            SelectList users = new SelectList(db.AspNetUsers, "Id", "UserName");
            ViewBag.AspNetUsers = users;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCaseRecord,Diagnosis,Treatment,IdPatient")] CartForPatient cartForPatient)
        {
            if (ModelState.IsValid)
            {
                db.CartForPatient.Add(cartForPatient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cartForPatient);
        }
        [Authorize(Roles = "doctor,admin")]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            CartForPatient cart = db.CartForPatient.Find(id);
            if (cart != null)
            {
                SelectList users = new SelectList(db.AspNetUsers, "Id", "UserName", cart.IdPatient);
                ViewBag.Users = users;
                return View(cart);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCaseRecord,Diagnosis,Treatment,IdPatient")] CartForPatient cartForPatient)
        {
            db.Entry(cartForPatient).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        [Authorize(Roles = "doctor,admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartForPatient cartForPatient = db.CartForPatient.Find(id);
            if (cartForPatient == null)
            {
                return HttpNotFound();
            }
            return View(cartForPatient);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CartForPatient cartForPatient = db.CartForPatient.Find(id);
            db.CartForPatient.Remove(cartForPatient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Search1(string user)
        {
            var allinfo = db.AspNetUsers.Where(a => a.UserName.Contains(user)).ToList();
            List<PatientViewModel> list = new List<PatientViewModel>();
            if (allinfo.Count <= 0)
            {
                return PartialView(list);
            }
            foreach (var item in allinfo)
            {
                list = PatientViewModel.Parse(item);
            }
            return PartialView(list);
        }
        public ActionResult InfoAboutPatient()
        {
            return View(new List<CartForPatient>());
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult ShowUser()
        {
            return View();
        }
    }
}

ClinicForAnimal1.2/Controllers/DoctorInfoController.cs
using ClinicForAnimal1._2.Models.DoctorInfo;
using System.Web.Mvc;
using System.Linq;
using System.Collections.Generic;
using System.Data.Entity;

namespace ClinicForAnimal1._2.Controllers
{
    [Authorize(Roles = "admin")]
    public class DoctorInfoController : Controller
    {
        ClinicForAnimalEntities doctorInfo = new ClinicForAnimalEntities ();
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(DoctorInfoForAdmin doc)
        {
            doctorInfo.DoctorInfoForAdmins.Add(doc);
            doctorInfo.SaveChanges();
            return View();
        }



        [AllowAnonymous]
        public ActionResult ShowInfoDoctor()
        {
            List<DoctorInfoForAdmin> info = doctorInfo.DoctorInfoForAdmins.ToList();
            return View(info);
        }



        [HttpGet]
        public ActionResult Delete(int? id)
        {
            DoctorInfoForAdmin doc = doctorInfo.DoctorInfoForAdmins.Find(id);
            if (doc == null)
            {
                HttpNotFound();
            }
            return View(doc);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteDoctor(int? id)
        {
            DoctorInfoForAdmin doc = doctorInfo.DoctorInfoForAdmins.Find(id);
            if (doc == null)
            {
                HttpNotFound();
            }
            doctorInfo.Entry(doc).State = EntityState.Deleted;
            doctorInfo.SaveChanges();
            return View();
        }



        [HttpGet]
        public ActionResult EditDoctor(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            DoctorInfoForAdmin doc = doctorInfo.DoctorInfoForAdmins.Find(id);
            if (doc != null)
            {
                return View(doc);
            }
            return HttpNotFound();
        }
        [HttpPost]
        public ActionResult EditDoctor(DoctorInfoForAdmin doc)
        {
            doctorInfo.Entry(doc).State = EntityState.Modified;
            doctorInfo.SaveChanges();
            return View();
        }
    }
}

ClinicForAnimal1.2/Controllers/ReviewsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ClinicForAnimal1._2.Models.Reviews;

namespace ClinicForAnimal1._2.Controllers
{
    public class ReviewsController : Controller
    {
        private ReviewsEntity db = new ReviewsEntity();
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Reviews.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NameOfPatient,Review1")] Review review)
        {
            if (ModelState.IsValid)
            {
                db.Reviews.Add(review);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(review);
        }

        [Authorize(Roles ="admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NameOfPatient,Review1")] Review review)
        {
            if (ModelState.IsValid)
            {
                db.Entry(review).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(review);
        }
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Review review = db.Reviews.Find(id);
            db.Reviews.Remove(review);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClinicForAnimal1.2/Controllers/VeterinarianServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClinicForAnimal1._2.Models.Services;

namespace ClinicForAnimal1._2.Controllers
{
    [Authorize(Roles = "admin")]
    public class VeterinarianServicesController : Controller
    {
        private VerServices db = new VerServices();

        public ActionResult Index()
        {
            return View(db.VeterinarianServices.ToList());
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VeterinarianService veterinarianService = db.VeterinarianServices.Find(id);
            if (veterinarianService == null)
            {
                return HttpNotFound();
            }
            return View(veterinarianService);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NameOfVeterinaryServices,UnitOfMeasurement,Cost,Category")] VeterinarianService veterinarianService)
        {
            if (ModelState.IsValid)
            {
                db.VeterinarianServices.Add(veterinarianService);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(veterinarianService);
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VeterinarianService veterinarianService = db.VeterinarianServices.Find(id);
            if (veterinarianService == null)
            {
                return HttpNotFound();
            }
            return View(veterinarianService);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NameOfVeterinaryServices,UnitOfMeasurement,Cost,Category")] VeterinarianService veterinarianService)
        {
            if (ModelState.IsValid)
            {
                db.Entry(veterinarianService).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(veterinarianService);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VeterinarianService veterinarianService = db.VeterinarianServices.Find(id);
            if (veterinarianService == null)
            {
                return HttpNotFound();
            }
            return View(veterinarianService);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            VeterinarianService veterinarianService = db.VeterinarianServices.Find(id);
            db.VeterinarianServices.Remove(veterinarianService);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [AllowAnonymous]
        public ActionResult ShowCategory()
        {
            List<VeterinarianService> info = db.VeterinarianServices.ToList();
            return View(info);
        }

        [AllowAnonymous]
        public ActionResult Categories(string category)
        {
            Categories info = new Categories
            {
                Services = db.VeterinarianServices.Where(p => category == null || p.Category == category),
                CurrentCategory = category
            };
            return View(info);
        }
    }
}

ClinicForAnimal1.2/Views/Reviews/Create.cshtml
@model ClinicForAnimal1._2.Models.Reviews.Review

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Login.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная страница", "Index", "Account")</li>
                    <li>@Html.ActionLink("Календар", "Index", "Home")</li>
                    <li>@Html.ActionLink("Доктора", "ShowInfoDoctor", "DoctorInfo")</li>
                    <li>@Html.ActionLink("Услуги и цены", "Categories", "VeterinarianServices")</li>
                    <li>@Html.ActionLink("Отзывы", "Index", "Reviews")</li>
                    <li>@Html.ActionLink("Администрирование", "InfoForAdmin", "Admin")</li>
                    <li>@Html.ActionLink("Информация для врачей", "Index", "AddDoctors")</li>
                    <li>@Html.ActionLink("Информация о карточки пациента", "InfoForPatient", "CartForPatient")</li>
                </ul>
            </div>
        </div>
    </div>
    <br />
    <div class="login">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Отзывы</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label("имя и фамилия")
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NameOfPatient, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NameOfPatient, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Сообщение")
                    <div class="col-md-10">
                        @foreach (var item in ViewData.ModelMetadata.Properties)
                        {
                            <div class="form-group">
                                @if (item.PropertyName == "Review1")
                                {

                                    @Html.TextArea(item.PropertyName, null,
                                new { @class = "form-control", rows = 5, cols = 75 })
                                }
                            </div>
                        }

                        @Html.ValidationMessageFor(model => model.Review1, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Отправить" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>


    <div>
        @Html.ActionLink("Вернуться к главному окну", "Index")
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

ClinicForAnimal1.2/Views/Reviews/Delete.cshtml
@model ClinicForAnimal1._2.Models.Reviews.Review

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Review</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.NameOfPatient)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.NameOfPatient)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Review1)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Review1)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

ClinicForAnimal1.2/Views/Reviews/Details.cshtml
@model ClinicForAnimal1._2.Models.Reviews.Review

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Review</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.NameOfPatient)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.NameOfPatient)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Review1)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Review1)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

ClinicForAnimal1.2/Views/Reviews/Edit.cshtml
@model ClinicForAnimal1._2.Models.Reviews.Review

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Review</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.NameOfPatient, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NameOfPatient, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NameOfPatient, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Review1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Review1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Review1, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

ClinicForAnimal1.2/Views/Reviews/Index.cshtml
@model IEnumerable<ClinicForAnimal1._2.Models.Reviews.Review>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Login.css" rel="stylesheet" />
</head>
<body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Главная страница", "Index", "Account")</li>
                        <li>@Html.ActionLink("Календарь", "Index", "Home")</li>
                        <li>@Html.ActionLink("Доктора", "ShowInfoDoctor", "DoctorInfo")</li>
                        <li>@Html.ActionLink("Услуги и цены", "Categories", "VeterinarianServices")</li>
                        <li>@Html.ActionLink("Отзывы", "Index", "Reviews")</li>
                        <li>@Html.ActionLink("Администрирование", "InfoForAdmin", "Admin")</li>
                        <li>@Html.ActionLink("Информация для врачей", "Index", "AddDoctors")</li>
                        <li>@Html.ActionLink("Информация о карточке пациента", "InfoAboutPatient", "CartForPatients1")</li>
                    </ul>
                </div>
            </div>
        </div>
    <div class="login">
        <p>
            @Html.ActionLink("Добавить отзыв", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.Label("Имя")
                </th>
                <th>
                    @Html.Label("Отзыв")
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NameOfPatient)
                    </td>
                    <td style="width:100px;">
                        @Html.DisplayFor(modelItem => item.Review1)
                    </td>
                </tr>
            }
        </table>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>